version: "3.7"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: anthonyss09/thebikeshop:bike-server
    container_name: myapp-node-server
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: bike-server-container
    command: /usr/src/app/node_modules/.bin/nodemon server.js
    volumes:
      - my-data:/user/src/app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  mongo:
    image: anthonyss09/thebikeshop:bike-mongo
    volumes:
      - my-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: anthonyss09/thebikeshop:bike-client
    container_name: myapp-react-client
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: bike-client-container
    command: npm run build
    volumes:
      - my-data:/user/app
    depends_on:
      - server
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  my-data:
  node_modules:
  web-root:
    driver: local
